---
# control
control:
  data_name: MNIST
  model_name: base
  formulation_mode: eps
# generate
generate:
  num_steps: 100
  guidance_scale: 2.
  eta: 1.
# experiment
pin_memory: True
num_workers: 2
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
resume_mode: 0
profile: False
